# Generated by Django 5.2 on 2025-12-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='plant_name',
            new_name='plan_name',
        ),
    ]
