# Generated by Django 5.2 on 2025-12-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_rename_plant_name_pricing_plan_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricing',
            table='pricing',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
