# Generated by Django 5.2 on 2025-12-19 01:48
from django.db import migrations


def create_default_pricing_plans(apps, schema_editor):
    Pricing = apps.get_model("pricing", "Pricing")

    plans = [
        {
            "plan_name": "Plano Básico",
            "price": 29.90,
            "description": "Plano básico para pequenos projetos",
        },
        {
            "plan_name": "Plano Profissional",
            "price": 59.90,
            "description": "Plano ideal para projetos em crescimento",
        },
        {
            "plan_name": "Plano Enterprise",
            "price": 99.90,
            "description": "Plano completo para grandes aplicações",
        },
    ]

    for plan in plans:
        Pricing.objects.get_or_create(
            plan_name=plan["plan_name"],
            defaults={
                "price": plan["price"],
                "description": plan["description"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0004_alter_pricing_table_alter_userprofile_table"),
    ]

    operations = [
        migrations.RunPython(create_default_pricing_plans),
    ]
